### ISSUE TITLE
Update SWS API to use Elasticsearch 7.9 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/sitewide-search-api#37]
Update the API for the SWS and autosuggest to use Elasticsearch 7.9

## Tasks:
1. Get same dataset, formatted for ES7 - #40 
2.

**Comment by VictoriaSunNIH** [comment]
Sample data is available already

**Comment by blairlearn** [comment]
In order to do this without rewriting our deserialization code, it is necessary to tweak the creation of the IElasticClient instance in the API shared code's startup/service registration.

https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/39
