### ISSUE TITLE
Create fixed data sets

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#40]
Create fixed sets of known search and autosuggest data for use in integration tests.

The same data should be used to create JSON files for ingestion into both Elasticsearch 5.6 and 7.9.

Please also attach (or provide links to) the index mapping files for both versions.

**Parent Issue:** #39

**Comment by zhuomingao** [comment]
[sitewide2.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6657935/sitewide2.json.gz)
[sitewide3.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6657960/sitewide3.json.gz)
[sitewide1.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6657963/sitewide1.json.gz)

**Comment by zhuomingao** [comment]
[cgovindex.txt](https://github.com/NCIOCPL/sitewide-search-api/files/6658082/cgovindex.txt)

**Comment by zhuomingao** [comment]
attached index mapping file and data files are specific to ES 7.9, will not work with ES 5.6.

**Comment by zhuomingao** [comment]
[cgovindex_ES56.txt](https://github.com/NCIOCPL/sitewide-search-api/files/6658236/cgovindex_ES56.txt)

**Comment by zhuomingao** [comment]
[sitewide2_es56.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6658491/sitewide2_es56.json.gz)
[sitewide1_es56.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6658496/sitewide1_es56.json.gz)
[sitewide3_es56.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6658499/sitewide3_es56.json.gz)

**Comment by bkline** [comment]
@zhuomingao I have updated the ticket (after consulting with @blairlearn) to reflect the fact that we need data and mappings for both indices (`cgov` and `autosg`) which support the SWS APIs. Please attach both to the ticket (ES56 and ES79) when you are able. Thanks!

**Comment by zhuomingao** [comment]
[autosg_es79.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6695120/autosg_es79.json.gz)
[autosg_es56.json.gz](https://github.com/NCIOCPL/sitewide-search-api/files/6695121/autosg_es56.json.gz)
[autosg_es56.txt](https://github.com/NCIOCPL/sitewide-search-api/files/6695134/autosg_es56.txt)
[autosg_es79.txt](https://github.com/NCIOCPL/sitewide-search-api/files/6695135/autosg_es79.txt)
