### ISSUE TITLE
Documentation bug for collection parameter

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/sitewide-search-api#41]
### Issue description
The [documentation](https://github.com/NCIOCPL/sitewide-search-api/blob/develop/src/NCI.OCPL.Api.SiteWideSearch/Controllers/AutosuggestController.cs#L58) which appears in the swagger interface says

> Collection is of the form {sitename}_{lang_code}.  Currently, {sitename} is always "cgov" and {lang_code} may        /// be either "en" (English) or "es" (Español).

In fact, the language code is a separate parameter. Appending it to the sitename in the `collection` parameter (separated by an underscore as specified in the documentation) results in a 500 ("Internal server error") response.

> **ESTIMATE** sp:1

### Steps to reproduce the issue

1.  Bring up the SWS swagger interface (https://webapis.cancer.gov/sitewidesearch/v1)
2. Click on Autosuggest
3. Click on GET /Autosuggest/{collection}/{language}/{term}
4. Click the **Try it out** button
5. Enter cgov_en in the field for the `collection` parameter
6. Enter en in the field for the `language` parameter
7. Enter hea in the `term` field
8. Click the **Execute** button

### What's the expected result?
- list of term containing the substring "hea"

### What's the actual result?
- 500 error

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/1634628/122417065-3a2c0580-cf57-11eb-84bf-2dbf7e89fbad.png)

**Comment by blairlearn** [comment]
Documentation has been updated.
