### ISSUE TITLE
The API should log errors

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/sitewide-search-api#44]
### Issue description
When the underlying Elasticsearch server return a response indicating problems, those problems should be logged.

> **ESTIMATE** sp:2

### Steps to reproduce the issue

1.  Delete the  Elasticsearch `cgov` index (or alias)
2. Submit `GET /Search/cgov/en/cancer` to the API server

### What's the expected result?
- Log the 404 ("no such index") error returned by the Elasticsearch server
- Return a response to the client indicating that the Elasticsearch server returned an error

### What's the actual result?
- The error returned by the Elasticsearch server is not logged
- A 500 response is returned to the client with the misleading message "Error connecting to search servers"

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/1634628/122811405-6f5d8e00-d29e-11eb-9e95-758c5ff0e28f.png) ![image](https://user-images.githubusercontent.com/1634628/122811438-7a182300-d29e-11eb-9dab-63ff8d932734.png)

**Comment by blairlearn** [comment]
Fixed in 2406bae431a05e9372cb3287e9c7cb02d8a1a8c8
