### ISSUE TITLE
Autosuggest ignores size parameter

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/sitewide-search-api#50]
### Issue description
*The Autosuggest feature documents the use of the `size` parameter to impose a ceiling on the number of terms to be returned to the caller. However, the [code](https://github.com/NCIOCPL/sitewide-search-api/blob/develop/src/NCI.OCPL.Api.SiteWideSearch/Controllers/AutosuggestController.cs#L99) always returns ten terms, or all matching terms, whichever is fewer.*

> **ESTIMATE** 1

### Steps to reproduce the issue

1.  `curl 'https://sitewidesearchapi.cancer.gov/sitewidesearch/v1/Autosuggest/cgov/en/liver?size=5'`
2. `curl 'https://sitewidesearchapi.cancer.gov/sitewidesearch/v1/Autosuggest/cgov/en/liver?size=10'`
3. `curl 'https://sitewidesearchapi.cancer.gov/sitewidesearch/v1/Autosuggest/cgov/en/liver?size=15'`

### What's the expected result?
- Results sets containing 5, 10, and 15 terms respectively

### What's the actual result?
- All results sets contain 10 terms

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/1634628/123155022-95696680-d435-11eb-9287-26768ef35dab.png)

### Patch
```diff
index 30c5c3b..2b17a65 100644
--- a/src/NCI.OCPL.Api.SiteWideSearch/Controllers/AutosuggestController.cs
+++ b/src/NCI.OCPL.Api.SiteWideSearch/Controllers/AutosuggestController.cs
@@ -96,7 +96,7 @@ namespace NCI.OCPL.Api.SiteWideSearch.Controllers
                 .File(templateName)
                 .Params(pd => pd
                     .Add("searchstring", term)
-                    .Add("my_size", 10)
+                    .Add("my_size", size)
                 )
             );
```
### Notes
Be sure to add integration tests to verify the correct behavior when the bug has been fixed.

**Comment by jfrank-nih** [comment]
@bkline I think this can be closed. At least, it works for me on the development branch currently. I'm updating the tests and noticed a comment in there to this ticket.

**Comment by bkline** [comment]
I see the comment on #42 (another of the bugs I reported) but not this one. Still, it's fixed (perhaps inadvertently). Closing.

**Comment by jfrank-nih** [comment]
Great. And I've got a test covering it that I'll put in a PR for @blairlearn this week.
