### ISSUE TITLE
Enabler: Refactor DOC search queries

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#61]
# Refactor DOC search queries to make the `{{my_site}}` criterion a top-level node, directly under the `query` key.

At present, in both the `search_doc_en.mustache` and `search_doc_es.mustache` templates, the portion of the query which filters the `{{my_site}}` parameter is nested in a `bool` sub-query near the beginning of the template.

The goal is to make `{{my_site}}` the final part of the query without affecting the output of the query.

The intent is two-fold:
1. This will allow the middle-tier adaptation to build up the query by optionally appending "...and limit it to this site."
2. This will accommodate an anticipated requirements change to allow DOC search to include results from multiple sites.

> **ESTIMATE** TBD

### Resources:
* [Search Templates](https://github.com/NCIOCPL/elasticsearch_config/tree/master/elastic/etc/scripts/cgov)

**Comment by zhuomingao** [comment]
{     "query": {
    "bool": {
   "filter":
        {"bool": {
        "should": [
          {
            "term": {
              "metatag.content-language": "en"
            }
          },
          {"bool": {
              "must_not": {
                  "exists": {
                      "field": "metatag.content-language"
                          }
                      }
                  }
          }
        ]
      }},
      "should": [
        {
          "term": {
            "type": {
              "value": "text/html",
              "boost": 2
            }
          }
        }
      ]
    ,
      "must": [
    
        {
          "bool": {
            "should": [
              {
                "match": {
                  "content": {
                    "query": "cancer",
                    "operator": "and",
                    "boost": 2
                  }
                }
              },
              {
                "match": {
                  "searchtitle": {
                    "query": "cancer",
                    "boost": 2
                  }
                }
              },
              {
                "match": {
                  "searchurl": {
                    "query": "cancer",
                    "boost": 3
                  }
                }
              },
              {
                "match_phrase": {
                  "content": {
                    "query": "cancer",
                    "boost": 3
                  }
                }
              },
              {
                "bool": {
                  "should": [
                    {
                      "match": {
                        "metatag.description": {
                          "query": "cancer",
                          "boost": 0.01
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {"bool": 
            {"must":
            [
            {"exists": {"field": "searchtitle" }},
            {"prefix": {"searchurl.raw": "dceg." } }
            ]
        }}
      ]
    }},
"_source":  false
, "sort":["_score", "url"]}
