### ISSUE TITLE
Enabler: Tests for search result weighting

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#62]
# Establish test scenarios (and actual tests) for search result weighting

* What scenarios should be tested?
  * Enumerate those scenarios in comments on this ticket, (e.g. "Certain page types should be in the 'top 10' for a given set of inputs.")
* What inputs to the search API will produce results demonstrating that scenario?
  * Fully exercising the API to demonstrate all the nuances may require multiple sets of inputs and result sets.
* Create a set of tests to put into the repository.
  * The expectation is that the tests will run successfully using the data in this project's `integration-tests` directory.

> **ESTIMATE** TBD

### Resources:
* Instructions, and set of support files (including data) for running the API locally under Docker are located in [the project's integration-tests directory](https://github.com/NCIOCPL/sitewide-search-api/tree/develop/integration-tests).

**Comment by zhuomingao** [comment]
for common search keywords like:
breast cancer
prostate cancer

CTHP and PDQ summaries should be returned as top 10 results

**Comment by blairlearn** [comment]
- Tests that rank CGDP-managed (WCMS) sites above sites not managed by CGDP (Req 1.1)
   - www
   - dceg
   - dcegconnect
   - mypart
   - nano
   - nciconnect
   - physics
- Tests that rank results based on content type
   1. HTML / Text
   2. PDF
   3. Other "Office" documents (.doc, .xls, .ppt)
   4. Exclude image files
-

**Comment by zhuomingao** [comment]
When the requirement was first created, there was only CGOV in WCMS, so based on that, only www.cancer.gov content is rated higher than none www.cancer.gov content.

**Comment by blairlearn** [comment]
We're going to take a different approach to this.
