### ISSUE TITLE
Enabler: Tests for languages

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#66]
# Establish test scenarios (and actual tests) for how the user's selected language affects search results.

For valid combinations of
* The main site (collection = `cgov`, site = `all`)
* DOC sites (collection = `doc`) including
  * top-level doc site
  * path-based site in English
  * path-based site in Spanish
* English and Spanish languages

Verify
* English search returns no Spanish results
* Spanish search returns no English results

> **ESTIMATE** TBD

### Resources:
* Instructions, and set of support files (including data) for running the API locally under Docker are located in [the project's integration-tests directory](https://github.com/NCIOCPL/sitewide-search-api/tree/develop/integration-tests).

**Comment by zhuomingao** [comment]
In English search, keyword: mama, should return only English results.

**Comment by blairlearn** [comment]
This test is challenging as it requires knowledge of a page's language.

_Possible_ validations:
- Check for the presence/absence of `/espanol/` in the result's `url` property.
- Check for  the presence of "- National Cancer Institute" vs "- Instituto Nacional del Cáncer" in the `title` attribute.

It will be necessary to review the test data to check how broadly those validations apply.  It _may_ be necessary to restrict the search to sites managed by the CancerGov Digital Platform.  (If so, collection = `doc` and site = `www.cancer.gov` would even work for the main site.)

**Comment by blairlearn** [comment]
We're going to take a different approach to this.
