### ISSUE TITLE
Enabler: Tests for the site parameter.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#70]
# Establish test scenarios (and actual tests) for how using values other than "all" for the site filter affects search results.

* What scenarios should be tested?
  * Enumerate those scenarios in comments on this ticket, (e.g. "Certain page types should be in the 'top 10' for a given set of inputs.")
* What inputs to the search API will produce results demonstrating that scenario?
  * Fully exercising the API to demonstrate all the nuances may require multiple sets of inputs and result sets.
* Create a set of tests to put into the repository.
  * The expectation is that the tests will run successfully using the data in this project's `integration-tests` directory.

> **ESTIMATE** TBD

### Resources:
* Instructions, and set of support files (including data) for running the API locally under Docker are located in [the project's integration-tests directory](https://github.com/NCIOCPL/sitewide-search-api/tree/develop/integration-tests).

**Comment by zhuomingao** [comment]
Scenario: cgov include sites other than cgov 
        Given path 'Search', 'cgov', 'en', 'FNLAC'
        And param size = 10
        When method get
        Then status 200
        And match $.results[1].url contains 'https://deainfo.nci.nih.gov/'

**Comment by zhuomingao** [comment]
Test for “The cgov collection ignores the site filter”
    


Scenario: cgov collection #67
        Given path 'Search', 'cgov', 'en', 'nanotechnology'
        And param size = 10
        And param site = 'chicken'
        When method get
        Then status 200
        And match each $.results[*].url contains 'www.cancer.gov'

**Comment by blairlearn** [comment]
Some scenarios to test
- the site parameter contains the url of a top-level site (e.g. dceg.cancer.gov or physics.cancer.gov)
- the site parameter contains the url of a path-based site (e.g. www.cancer.gov/rare-brain-spine-tumor/)

For both of these, verify the results only start with the specified domain.
It should also shouldn't be just the first 10 results. (That could be specify a large results size; it could also be checking a few ranges.)

A negative scenario: Test for completely nonsense site values: `asdfjkl`, `www.google.com`, `ʌoƃ˙ɹǝɔuɐɔ˙ʍʍʍ`, or `ʍʍʍ˙ɔɐuɔǝɹ˙ƃoʌ`  Any of these (especially the last two!) would be expected to return nothing.

**Comment by blairlearn** [comment]
@zhuomingao - that's a test case which should be tested.  Specifically: Verify that specifying various values for the `site` parameter does *NOT* change the results when the `collection` parameter is set to `cgov`.

**Comment by blairlearn** [comment]
@lburack - What is the _expected_ behavior if the user specifies the `doc` collection and `all` for the site parameter?

The  current implementation will restrict the results to site beginning with the string "all", but that's a naive implementation.

Possible answers include (but aren't limited to): "It's a bad request" or "It should retrieve results for all sites."

**Comment by blairlearn** [comment]
We're going to take a different approach to this.
