### ISSUE TITLE
Enabler: Verify images are excluded from search results

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#75]
# Create a set of tests to verify that images are not returned by site wide search.

Create tests varying among these parameters
- Search for terms which are usually in the title, browser title, metakeyword, meta description, and first paragraph of a page content type.
- Search for terms which are more often used in fields of an image content type than a page type.
- Repeat for both English and Spanish

In all cases, verify that none of the returned documents are images.  This should not be limited to just the first page of results.  (This may be accomplished by specifying a large value for the `size` parameter, altering the `from` parameter, or some combination of the two.)

Additionally, vary the search parameters  (It is not necessary to enumerate all combinations)

* Sites in the `cgov` collection, using `all` for the site parameter
* Sites in the `doc` collection, using a top-level site (e.g. dceg.cancer.gov)
* Sites in the `doc` collection, using a path-based site (e.g. www.cancer.gov/nano)

*Description of what is to be accomplished.*
*Examples:*
* *Initial Setup of Dev Tier*
* *Create Application Framework*
* *Define Unit Test Approach*
* *Research UX Patterns for Search*

> **ESTIMATE** TBD

### Resources:
- [Sitewide Search Swagger page](https://webapis.cancer.gov/sitewidesearch/v1/index.html)

**Comment by zhuomingao** [comment]
@blairlearn ,  contentType field in lots of cases are null in the response, so how can we test it is a image or not?

**Comment by blairlearn** [comment]
@zhuomingao Does Nutch even index images?

**Comment by zhuomingao** [comment]
I think, we configured nutch not to crawl images based on suffix.

**Comment by blairlearn** [comment]
Please check on that.
